### ISSUE TITLE
Cannot make migrations

### ISSUE THREAD

**Issue by Avin-Mathew** [ice-creams/graphql-social-auth-template#2]
```
(env) avin@avin-pc:~/Documents/git/graphql-social-auth-template/graphql-social-auth-template$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/avin/Documents/git/graphql-social-auth-template/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/avin/Documents/git/graphql-social-auth-template/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/home/avin/Documents/git/graphql-social-auth-template/env/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/avin/Documents/git/graphql-social-auth-template/env/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/avin/Documents/git/graphql-social-auth-template/env/lib/python3.5/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/avin/Documents/git/graphql-social-auth-template/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'social_auth'
(env) avin@avin-pc:~/Documents/git/graphql-social-auth-template/graphql-social-auth-template$ 

```

**Comment by mongkok** [comment]
Hi @Avin-Mathew,

```
ImportError: No module named 'social_auth'
```

have you correctly installed the requirements?
https://github.com/ice-creams/graphql-social-auth-template/blob/master/Pipfile

```sh
$ pipenv install
```
